version: '3'

services:
  web:
    container_name: one-web
    image: jiker/one-web:0.0.1
    restart: always
    tty: true
    ports: 
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
  api:
    # build: 
    #   context: ./one-api
    #   dockerfile: Dockerfile
    #   args:
    #    - username=tommywu
    #    - password=Wjs007008
    image: jiker/one-api:0.0.1
    container_name: one-api
    tty: true
    ports:
      - 9000:9000
    volumes:
      - "$PWD:/var/www"
    #   - ./www/api:/jikerone/api
    #   - ./www/git/api:/source/api
    user: www-data
    # command: ./one-api/run.sh
    command:
      - /bin/sh
      - -c
      - |
        php artisan key:generate  
        echo -e "yes" | php artisan jwt:secret 
        php artisan migrate 
        php artisan db:seed --class=PermissionsSeeder 
        php artisan passport:keys  
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
  mysql-master:
    image: daocloud.io/mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
      - MYSQL_DATABASE=one
  mysql-slave:
    image: daocloud.io/mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
      - MYSQL_DATABASE=one
  redis:
    image: redis
    container_name: one-redis
    ##command: redis-server --requirepass yourpassword
    tty: true
    ports:
      - 6379:6379
    volumes:
      - db_data:/data
volumes:
  db_data:
