version: '3'

services:
  mysql-master:
    image: daocloud.io/mysql:5.7.25
    container_name: mysql-master
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
      - MYSQL_DATABASE=one
    volumes:
      - "./mysql:/etc/mysql/conf.d"
  mysql-slave:
    image: daocloud.io/mysql:5.7.25
    container_name: mysql-slave
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
      - MYSQL_DATABASE=one
    volumes:
      - "./mysql:/etc/mysql/conf.d"
  redis:
    image: redis
    container_name: one-redis
    tty: true
    ports:
      - 6379:6379
  web:
    container_name: one-web
    image: jiker/one-web:0.0.1
    restart: always
    tty: true
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
  api:
    image: jiker/one-api:0.0.1
    container_name: one-api
    tty: true
    ports:
      - "9002:9000"
      - "9999:22"
    volumes:
      - "$PWD:/var/www"
      - "./env:/jikerone/api/storage/logs"
    links:
        - "mysql-master:mysql-master"
        - "mysql-slave:mysql-slave"
        - "redis:redis"
    command:
      - /bin/sh
      - -c
      - |
        php artisan key:generate  
        php artisan jwt:secret 
        php artisan telescope:install
        php artisan migrate --force 
        php artisan db:seed --class=PermissionsSeeder 
        php artisan passport:keys 
  demo:
    image: centos:7
    container_name: demo
    tty: true
    links:
      - "mysql-master:mysql-master"
      - "mysql-slave:mysql-slave"
      - "redis:redis"
