version: '3'

services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
  redis:
    image: redis
    container_name: one-redis
    restart: always
    ##command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

