version: '3'

services:
  oneapi:
    build: 
      context: ./one-api
      dockerfile: Dockerfile
      args:
       - username=tommywu
       - password=Wjs007008
    image: oneapi:gm
    container_name: one-api
    volumes:
      - /jikerone/api:/var/wwwroot/api
      - /api:/var/git/api
    user: produser
    command: /bin/sh -c php artisan key:generate && php artisan jwt:secret && php artisan migrate && php artisan db:seed --class=PermissionsSeeder && php artisan passport:keys
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
    networks:
      jiker_one_net:
        ipv4_address: 192.168.0.100
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
    networks:
      jiker_one_net:
        ipv4_address: 192.168.0.252
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
    networks:
      jiker_one_net:
        ipv4_address: 192.168.0.251 
  redis:
    image: redis
    container_name: one-redis
    ##command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      jiker_one_net:
        ipv4_address: 192.168.0.249
networks:
    jiker_one_net:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.0.0/16
