version: '3'

services:
  web:
    container_name: one-web
    image: jiker/one-web:0.0.1
    restart: always
    tty: true
    ports: 
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
  api:
    build: 
      context: ./one-api
      dockerfile: Dockerfile
      args:
       - username=tommywu
       - password=Wjs007008
    image: oneapi:gm
    container_name: one-api
    tty: true
    ports:
      - 9002:9002
    # volumes:
    #   - ./www/api:/jikerone/api
    #   - ./www/git/api:/source/api
    user: www-data
    # command: ./one-api/run.sh
    command:
      - /bin/sh
      - -c
      - |
        php artisan key:generate 
        echo -e "\n" | php artisan jwt:secret 
        echo -e "\n" | php artisan migrate 
        echo -e "\n" | php artisan db:seed --class=PermissionsSeeder 
        echo -e "\n" | php artisan passport:keys  
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    tty: true
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
  redis:
    image: redis
    container_name: one-redis
    ##command: redis-server --requirepass yourpassword
    tty: true
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
