version: '3'

services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
    networks:
      jiker_one_net:
        ipv4_address: 172.17.0.252
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=api123
    networks:
      jiker_one_net:
        ipv4_address: 172.17.0.251 
  redis:
    image: redis
    container_name: one-redis
    restart: always
    ##command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      jiker_one_net:
        ipv4_address: 172.17.0.249
networks:
    jiker_one_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.17.0.0/16
                - gateway: 172.17.0.1